<?php 
// ebay PHP at defines
DEFINE( "EBAY_NOTHING", null );

DEFINE( "EBAY_ERR_SUCCESS", "0" );
DEFINE( "EBAY_ERR_ERROR", "1" );
DEFINE( "EBAY_ERR_WARNING", "2" );
// this are defines for cURL
// a few are not documented, but the names should be
// rather descriptive
DEFINE( 'CURLOPT_PROXYTYPE', 101 );
// DEFINE( 'CURLOPT_PROXYUSERPWD', 6 );
// DEFINE( 'CURLOPT_HTTPPROXYTUNNEL', 61 );
DEFINE( 'CURLOPT_PROXYAUTH', 111 );
DEFINE( 'CURLAUTH_NONE', 0 );
DEFINE( 'CURLAUTH_BASIC', 0 );
DEFINE( 'CURLAUTH_DIGEST', 1 );
DEFINE( 'CURLAUTH_GSSNEGOTIATE', 2 );
DEFINE( 'CURLAUTH_NTLM', 4 );
DEFINE( 'CURLAUTH_ANY', 7 );

DEFINE( 'CURLPROXY_HTTP', 0 );
DEFINE( 'CURLPROXY_SOCKS4', 4 );
DEFINE( 'CURLPROXY_SOCKS5', 5 );

DEFINE( 'CURLOPT_BUFFERSIZE', 98 );

?>