<?php
  /*
  Module: Information Pages Unlimited
          File date: 2007/02/17 
          Based on the FAQ script of adgrafics
          Adjusted by Joeri Stegeman (joeri210 at yahoo.com), The Netherlands

  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com

  Released under the GNU General Public License
  */
require('includes/application_top.php');
  //BOF:authorization_check
  handle_authorization(basename(__FILE__));
  //EOF:authorization_check
// Include current language file, if not exists, fall use English (Why is this not a standard procedure in OsCommerce?)
if(file_exists(DIR_WS_LANGUAGES . $language . '/' . "lanes.php")) {
	include(DIR_WS_LANGUAGES . $language . '/' . "lanes.php");
	}
else {
	include(DIR_WS_LANGUAGES . 'english/' . "lanes.php");
}

$languages = tep_get_languages();


//$info_group['locked'] = ''; // DEBUG, to ignore locked fields


// Create additional information records for unknown languages
// NOTE: This is a function with some overhead, but is needed as this is an add-on
//       and the new languages are not automatically generated by languages.php

//paggination
 $start = 0;            
    $end = 15;
function tep_get_information_list ($language_id = 0) {
	global $languages_id;
	if ($language_id == 0) $language_id = $languages_id;
    
     $start = 0;            
    $end = 15;
    $where = '';
    if($_GET['ranges_id']) $where = " AND l.ranges_id = '".$_GET['ranges_id']."' ";
    
   
   // echo $paggination;
    
    if($_GET['page'])
    {
        $start = $_GET['page']*$end; 
    }                

    $information_query = tep_db_query("SELECT l.lanes_id as lanes_id, l.lanes_name as lanes_name, l.descr as descr , l.sort_order as sort_order, l.status as status,r.ranges_name as ranges_name FROM ".TABLE_LANES." as l,".TABLE_RANGES." as r where l.ranges_id = r.ranges_id ".$where." ORDER BY l.ranges_id,l.sort_order ASC LIMIT ".$start." , ".$end);

	$c=0;
	while ($buffer = tep_db_fetch_array($information_query)) {
		$result[$c] = $buffer;
		$c++;
	}
	return $result;
}

function tep_get_information_entry ($lanes_id) {
	
	$information_query = tep_db_query("SELECT * FROM ".TABLE_LANES." WHERE lanes_id = '".$lanes_id."'");
	
	$information = tep_db_fetch_array($information_query);

	return $information;
}

$warning = tep_image(DIR_WS_ICONS . 'warning.gif', WARNING_INFORMATION); 

function error_message($error) {
	global $warning;
	switch ($error) {
		case "20":return "<tr class=messageStackError><td>$warning ." . ERROR_20_INFORMATION . "</td></tr>";break;
		case "80":return "<tr class=messageStackError><td>$warning " . ERROR_80_INFORMATION . "</td></tr>";break;
		default:return $error;
	}
}

?>
<body marginwidth="0" marginheight="0" topmargin="0" bottommargin="0" leftmargin="0" rightmargin="0" bgcolor="#FFFFFF">
<?PHP
// Tiny MCE WYISIWYG detection and include
if (file_exists("tiny_mce/tiny_mce.js")) { $tiny_mce = "tiny_mce/tiny_mce.js"; }
elseif (file_exists("includes/javascript/tiny_mce/tiny_mce.js")) { $tiny_mce = "includes/javascript/tiny_mce/tiny_mce.js"; }
else $tiny_mce = '';
if($tiny_mce) {
echo '<script language="javascript" type="text/javascript" src="' . $tiny_mce . '"></script>
<script language="javascript" type="text/javascript">
tinyMCE.init({
mode : "textareas",
theme : "advanced",
relative_urls : false,
remove_script_host : false,
document_base_url : "' .HTTP_SERVER . '",

plugins : "table,advhr,advimage,ibrowser,advlink,emotions,preview,flash,print,contextmenu",
theme_advanced_buttons1_add : "fontselect,fontsizeselect",
theme_advanced_buttons2_add : "separator,preview,separator,forecolor,backcolor",
theme_advanced_buttons2_add_before: "cut,copy,paste,separator",
theme_advanced_buttons3_add_before : "tablecontrols,separator",
theme_advanced_buttons3_add : "emotions,flash,advhr,separator,print,ibrowser",
theme_advanced_toolbar_location : "top",
theme_advanced_toolbar_align : "left",
theme_advanced_path_location : "bottom",
extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
external_link_list_url : "example_data/example_link_list.js",
external_image_list_url : "example_data/example_image_list.js",
flash_external_list_url : "example_data/example_flash_list.js"
});
</script>';
}
?>
<!-- header //-->
<?php require(DIR_WS_INCLUDES . 'header.php'); ?>
<!-- header_eof //-->

<!-- body //-->

         <section>
         <!-- START Page content-->
         <section class="main-content">
            <h3>Lanes Manager /
               <br>
            </h3>
            <!-- START panel-->
            <div class="panel panel-default">
               
               <!-- START table-responsive-->
               
               <div class="table-responsive">
               <!-- START your table-->
<table class="table table-bordered table-hover">
  <tr>
    <!-- body_text //-->
    <td>
<table class="table table-bordered table-hover">
<tr><td align=right><?php //echo $languages_id; ?></td></tr>
<?
switch($_REQUEST['lane_action']) {

case "Added":
	$data = tep_get_information_list();
	$no = 1;
	if (sizeof($data) > 0) {
		while (list($key, $val)=each($data)) {$no++; }	
	}
	$title = ADD_QUEUE_INFORMATION . " #$no";
	echo tep_draw_form('',FILENAME_LANES_MANAGER, 'lane_action=AddSure');
	//echo tep_draw_hidden_field('gID', $gID);
	include('lanes_form.php');
	break;

case "AddSure":
	if($_POST['ranges_id'] && $_POST['lanes_name'] && ($_POST['status']==0 || $_POST['status']==1))
	{
		if(isset($_POST['status']))
			$sql_data_array['status'] = tep_db_prepare_input($_POST['status']);
			
		if(isset($_POST['lanes_name']))
			$sql_data_array['lanes_name'] = tep_db_prepare_input($_POST['lanes_name']);
			
		if(isset($_POST['sort_order']))
			$sql_data_array['sort_order'] = tep_db_prepare_input($_POST['sort_order']);	
			
		if(isset($_POST['descr']))	
			$sql_data_array['descr'] = tep_db_prepare_input($_POST['descr']);
			
		if(isset($_POST['ranges_id']))	
			$sql_data_array['ranges_id'] = tep_db_prepare_input($_POST['ranges_id']);	

		tep_db_perform(TABLE_LANES, $sql_data_array);

		$lanes_id = tep_db_insert_id();
		
		$data = tep_get_information_list();
		$title = tep_image(DIR_WS_ICONS . 'confirm_red.gif', CONFIRM_INFORMATION) .SUCCED_INFORMATION . ADD_QUEUE_INFORMATION . " $sort_order ";
		//include('lanes_list.php');
		unset($data);
		?>
			<script>
				location.href='<?php echo FILENAME_LANES_MANAGER; ?>';
			</script>
		<?php
	} else {$error="80";}
	break;

case "Edit":
	if ($lanes_id = $_REQUEST['lanes_id']) {
		$edit = tep_get_information_entry($lanes_id);
		$data = tep_get_information_list();
		$button = array("Update");
		$title = EDIT_ID_INFORMATION . " $lanes_id";
		echo tep_draw_form('',FILENAME_LANES_MANAGER, 'lane_action=Update');
		echo tep_draw_hidden_field('lanes_id', $lanes_id);
		//echo tep_draw_hidden_field('gID', $gID);
		include('lanes_form.php');
	}
	else {$error="80";}
	break;

case "Update":
	if ((int)$_POST['lanes_id']) 
	{
      
			$sql_data_array = array();
			
			if(isset($_POST['status']))
			$sql_data_array['status'] = tep_db_prepare_input($_POST['status']);
			
			if(isset($_POST['lanes_name']))			
			$sql_data_array['lanes_name'] = tep_db_prepare_input($_POST['lanes_name']);
			
			if(isset($_POST['sort_order']))			
			$sql_data_array['sort_order'] = tep_db_prepare_input($_POST['sort_order']);
			
			if(isset($_POST['descr']))
			$sql_data_array['descr'] = tep_db_prepare_input($_POST['descr']);
			
			if(isset($_POST['ranges_id']))
			$sql_data_array['ranges_id'] = tep_db_prepare_input($_POST['ranges_id']);

			if(count($sql_data_array) > 0) {
				tep_db_perform(TABLE_LANES, $sql_data_array, 'update', "lanes_id = '" . (int)$_POST['lanes_id'] . "'");
			}
			
		
		$data = tep_get_information_list();
		$title = "$confirm " . UPDATE_ID_INFORMATION . " $lanes_id " . SUCCED_INFORMATION . "";
		include('lanes_list.php');
	} else {$error="80";}
	break;

case 'status':
	if ($status == '1') {
		$vivod=DEACTIVATION_ID_INFORMATION;
		tep_db_query("update " . TABLE_LANES . " set status = '0' where lanes_id = '" . (int)$lanes_id . "'");
	} 
	else {
		$vivod=ACTIVATION_ID_INFORMATION;
		tep_db_query("update " . TABLE_LANES . " set status = '1' where lanes_id = '" . (int)$lanes_id . "'");
	}
	$data=tep_get_information_list();
	$title="$confirm $vivod $lanes_id " . SUCCED_INFORMATION . "";
	include('lanes_list.php');
	break;

case "Delete":
	if ($lanes_id = $_GET['lanes_id']) {
		$delete = tep_get_information_entry($lanes_id);
		$data = tep_get_information_list();
		$title = DELETE_CONFIRMATION_ID_INFORMATION . " $lanes_id";
		echo '<tr><td>' . $title . '</td></tr>';
		echo '<tr><td align=left>' . ENTRY_TITLE . '</td></tr>';
		echo '<tr><td>' . $delete['lanes_name'] . '</td></tr>';
		echo '<tr><td></td></tr><tr><td align=right>';
		echo tep_draw_form('',FILENAME_LANES_MANAGER, "lane_action=DelSure&lanes_id=" . $delete['lanes_id']);
		echo tep_draw_hidden_field('lanes_id', $lanes_id);
		//echo tep_draw_hidden_field('gID', $gID);
		echo tep_image_submit('button_delete_b.gif', IMAGE_DELETE);
		echo '&nbsp;<a href="' . tep_href_link(FILENAME_LANES_MANAGER, "", 'NONSSL') . '">' . tep_image_button('button_cancel_b.gif', IMAGE_CANCEL) . '</a>';
		echo "</form></td></tr>";
	} 
	else {$error="80";}
	break;


case "DelSure":
	if ($lanes_id = $_GET['lanes_id']) {
		tep_db_query("delete from " . TABLE_LANES . " where lanes_id = '" . (int)$lanes_id . "'");
		$title = "$confirm " . DELETED_ID_INFORMATION . " $lanes_id " . SUCCED_INFORMATION . "";
		include('lanes_list.php');
	} 
	else {$error="80";}
	break;

default:
	$data = tep_get_information_list();
	$title = MANAGER_INFORMATION . " <FONT SIZE='-1'>/ " . $info_group['information_group_title'] . "</FONT>";
	include('lanes_list.php');
	flush();
//	tep_update_information_languages();
} // END SWITCH


if ($error) {
	$content=error_message($error);
	echo $content;
	$data = tep_get_information_list();
	$no = 1;
	if (sizeof($data) > 0) {
		while (list($key, $val)=each($data)) {$no++; }	
	}
	$title = ADD_QUEUE_INFORMATION . " $no";
	echo tep_draw_form('',FILENAME_LANES_MANAGER, 'lane_action=AddSure');
	//echo tep_draw_hidden_field('gID', $gID);
	include('lanes_form.php');
}
?>
</table></td>


<!-- body_text_eof //-->
  </tr>
</table>  
               <!-- END your table-->
<!-- body_eof //-->

<!-- footer //-->
<?php require(DIR_WS_INCLUDES . 'footer.php'); ?>
<!-- footer_eof //-->

<?php require(DIR_WS_INCLUDES . 'application_bottom.php'); ?>