<?php
  /*
  Module: Information Pages Unlimited
          File date: 2007/02/17 
          Based on the FAQ script of adgrafics
          Adjusted by Joeri Stegeman (joeri210 at yahoo.com), The Netherlands

  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com

  Released under the GNU General Public License
  */
require('includes/application_top.php');
  //BOF:authorization_check
  handle_authorization(basename(__FILE__));
  //EOF:authorization_check
//BOF RANGE LOGO 09-JAN-2014  
define('RANGE_LOGO', HTTP_CATALOG_SERVER.'/'.DIR_WS_IMAGES.'ranges/');
define('RANGE_LOGO_PATH', DIR_FS_CATALOG.DIR_WS_IMAGES.'ranges/');
//EOF RANGE LOGO 09-JAN-2014  
// Include current language file, if not exists, fall use English (Why is this not a standard procedure in OsCommerce?)
if(file_exists(DIR_WS_LANGUAGES . $language . '/' . "ranges.php")) {
	include(DIR_WS_LANGUAGES . $language . '/' . "ranges.php");
	}
else {
	include(DIR_WS_LANGUAGES . 'english/' . "ranges.php");
}

$languages = tep_get_languages();


//$info_group['locked'] = ''; // DEBUG, to ignore locked fields


// Create additional information records for unknown languages
// NOTE: This is a function with some overhead, but is needed as this is an add-on
//       and the new languages are not automatically generated by languages.php

function tep_get_information_list ($language_id = 0) {
	global $languages_id;
	if ($language_id == 0) $language_id = $languages_id;

    $information_query = tep_db_query("select * from " . TABLE_RANGES . " order by `ranges_name` asc ");

	$c=0;
	while ($buffer = tep_db_fetch_array($information_query)) {
		$result[$c] = $buffer;
		$c++;
	}
	return $result;
}

function tep_get_information_entry ($information_id, $language_id = 0, $column = '') {
	global $languages_id;
	if ($language_id == 0) $language_id = $languages_id;

	$information_query = tep_db_query("select * from " . TABLE_RANGES . " where ranges_id = '" . (int)$information_id . "'");
	$information = tep_db_fetch_array($information_query);

	if(!empty($column)) return $information[$column]; 
	else return $information;
}

$warning = tep_image(DIR_WS_ICONS . 'warning.gif', WARNING_INFORMATION); 

function error_message($error) {
	global $warning;
	switch ($error) {
		case "20":return "<tr class=messageStackError><td>$warning ." . ERROR_20_INFORMATION . "</td></tr>";break;
		case "80":return "<tr class=messageStackError><td>$warning " . ERROR_80_INFORMATION . "</td></tr>";break;
		default:return $error;
	}
}

?>
<!doctype html public "-//W3C//DTD HTML 4.01 Transitional//EN">
<html <?php echo HTML_PARAMS; ?>>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=<?php echo CHARSET; ?>">
<title><?php echo TITLE; ?></title>
<link rel="stylesheet" type="text/css" href="includes/stylesheet.css">

<?PHP
// Tiny MCE WYISIWYG detection and include
if (file_exists("tiny_mce/tiny_mce.js")) { $tiny_mce = "tiny_mce/tiny_mce.js"; }
elseif (file_exists("includes/javascript/tiny_mce/tiny_mce.js")) { $tiny_mce = "includes/javascript/tiny_mce/tiny_mce.js"; }
else $tiny_mce = '';
if($tiny_mce) {
echo '<script language="javascript" type="text/javascript" src="' . $tiny_mce . '"></script>
<script language="javascript" type="text/javascript">
tinyMCE.init({
mode : "textareas",
theme : "advanced",
relative_urls : false,
remove_script_host : false,
document_base_url : "' .HTTP_SERVER . '",

plugins : "table,advhr,advimage,ibrowser,advlink,emotions,preview,flash,print,contextmenu",
theme_advanced_buttons1_add : "fontselect,fontsizeselect",
theme_advanced_buttons2_add : "separator,preview,separator,forecolor,backcolor",
theme_advanced_buttons2_add_before: "cut,copy,paste,separator",
theme_advanced_buttons3_add_before : "tablecontrols,separator",
theme_advanced_buttons3_add : "emotions,flash,advhr,separator,print,ibrowser",
theme_advanced_toolbar_location : "top",
theme_advanced_toolbar_align : "left",
theme_advanced_path_location : "bottom",
extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
external_link_list_url : "example_data/example_link_list.js",
external_image_list_url : "example_data/example_image_list.js",
flash_external_list_url : "example_data/example_flash_list.js"
});
</script>';
}
?>

</head>
<body marginwidth="0" marginheight="0" topmargin="0" bottommargin="0" leftmargin="0" rightmargin="0" bgcolor="#FFFFFF">
<!-- header //-->
<?php require(DIR_WS_INCLUDES . 'header.php'); ?>
<!-- header_eof //-->

<!-- body //-->
<table width="780" border="0" align="center" cellpadding="2" cellspacing="2">
  <tr>
    <!-- body_text //-->
    <td width="100%" valign="top">
<table border=0 width="100%">
<tr><td align=right><?php //echo $languages_id; ?></td></tr>
<?
switch($_REQUEST['range_action']) {

case "Added":
	$data = tep_get_information_list();
	$no = 1;
	if (sizeof($data) > 0) {
		while (list($key, $val)=each($data)) {$no++; }	
	}
	$title = ADD_QUEUE_INFORMATION . " #$no";
	echo tep_draw_form('',FILENAME_RANGES_MANAGER, 'range_action=AddSure', 'post', 'enctype="multipart/form-data"');
	//echo tep_draw_hidden_field('gID', $gID);
	include('ranges_form.php');
	break;

case "AddSure":
	
	if(isset($_POST['status']))
		$sql_data_array['status'] = tep_db_prepare_input($_POST['status']);
		
	if(isset($_POST['ranges_name']))
		$sql_data_array['ranges_name'] = tep_db_prepare_input($_POST['ranges_name']);
		
	if(isset($_POST['descr']))	
		$sql_data_array['descr'] = tep_db_prepare_input($_POST['descr']);
        
    if(isset($_POST['added']))	
		$sql_data_array['added'] = date('Y-m-d H:i:s');
        
    if(isset($_POST['calculate_via']))	
		$sql_data_array['calculate_via'] = tep_db_prepare_input($_POST['calculate_via']);                                        

    if(isset($_POST['day_hours']))	
		$sql_data_array['day_hours'] = tep_db_prepare_input($_POST['day_hours']);                    

	//BOF RANGE LOGO 09-JAN-2014  
	if (is_uploaded_file($_FILES['logo']['tmp_name'])) {
		$tmp_name = $_FILES["logo"]["tmp_name"];
        $name = rand(10000000,99999999).$_FILES["logo"]["name"];
        if(move_uploaded_file(RANGE_LOGO_PATH.$tmp_name, $name)) {
			$sql_data_array['logo'] = tep_db_prepare_input($name);
		}	
	}
	//EOF RANGE LOGO 09-JAN-2014  
		
	tep_db_perform(TABLE_RANGES, $sql_data_array);

	$ranges_id = tep_db_insert_id();

	
	$data = tep_get_information_list();
	$title = tep_image(DIR_WS_ICONS . 'confirm_red.gif', CONFIRM_INFORMATION) .SUCCED_INFORMATION . ADD_QUEUE_INFORMATION . " $sort_order ";
	include('ranges_list.php');
	unset($data);
	break;

case "Edit":
	if ($ranges_id = $_REQUEST['ranges_id']) {
		$edit = tep_get_information_entry($ranges_id);
		$data = tep_get_information_list();
		$button = array("Update");
		$title = EDIT_ID_INFORMATION . " $ranges_id";
		echo tep_draw_form('',FILENAME_RANGES_MANAGER, 'range_action=Update', 'post','enctype="multipart/form-data"');
		echo tep_draw_hidden_field('ranges_id', $ranges_id);
		//echo tep_draw_hidden_field('gID', $gID);
		include('ranges_form.php');
	}
	else {$error="80";}
	break;

case "Update":
	if ((int)$_POST['ranges_id']) 
	{
      
			$sql_data_array = array();
			
			if(isset($_POST['status']))
			$sql_data_array['status'] = tep_db_prepare_input($_POST['status']);
			
			if(isset($_POST['ranges_name']))			
			$sql_data_array['ranges_name'] = tep_db_prepare_input($_POST['ranges_name']);
			
			if(isset($_POST['descr']))
			$sql_data_array['descr'] = tep_db_prepare_input($_POST['descr']);
            
            if(isset($_POST['calculate_via']))
			$sql_data_array['calculate_via'] = tep_db_prepare_input($_POST['calculate_via']);
            
            if(isset($_POST['day_hours']))	
			$sql_data_array['day_hours'] = tep_db_prepare_input($_POST['day_hours']);
            
			//BOF RANGE LOGO 09-JAN-2014  
			if (is_uploaded_file($_FILES['logo']['tmp_name'])) {
				$tmp_name = $_FILES["logo"]["tmp_name"];
				$name = rand(10000000,99999999).$_FILES["logo"]["name"];
				if(move_uploaded_file($tmp_name, RANGE_LOGO_PATH.$name)) { 
					@unlink(RANGE_LOGO_PATH.$_POST['logoname']);
					$sql_data_array['logo'] = tep_db_prepare_input($name);
				}	
			}
			//EOF RANGE LOGO 09-JAN-2014    
            
			if(count($sql_data_array) > 0) {
				tep_db_perform(TABLE_RANGES, $sql_data_array, 'update', "ranges_id = '" . (int)$_POST['ranges_id'] . "'");
			}
		
		$data = tep_get_information_list();
		$title = "$confirm " . UPDATE_ID_INFORMATION . " $ranges_id " . SUCCED_INFORMATION . "";
		include('ranges_list.php');
	} else {$error="80";}
	break;

case 'status':
	if ($status == '1') {
		$vivod=DEACTIVATION_ID_INFORMATION;
		tep_db_query("update " . TABLE_RANGES . " set status = '0' where ranges_id = '" . (int)$ranges_id . "'");
	} 
	else {
		$vivod=ACTIVATION_ID_INFORMATION;
		tep_db_query("update " . TABLE_RANGES . " set status = '1' where ranges_id = '" . (int)$ranges_id . "'");
	}
	$data=tep_get_information_list();
	$title="$confirm $vivod $ranges_id " . SUCCED_INFORMATION . "";
	include('ranges_list.php');
	break;

case "Delete":
	if ($ranges_id = $_GET['ranges_id']) {
		$delete = tep_get_information_entry($ranges_id);
		$data = tep_get_information_list();
		$title = DELETE_CONFIRMATION_ID_INFORMATION . " $ranges_id".'<br >Deleting this range will also delete all related lanes.';
		echo '<tr class=pageHeading><td>' . $title . '</td></tr>';
		echo '<tr class=dataTableHeadingRow><td align=left class=dataTableHeadingContent>' . ENTRY_TITLE . '</td></tr>';
		echo '<tr><td class="dataTableContent" bgcolor="#DEE4E8" style="line-height: 18px;">' . $delete['ranges_name'] . '</td></tr>';
		echo '<tr><td></td></tr><tr><td align=right>';
		echo tep_draw_form('',FILENAME_RANGES_MANAGER, "range_action=DelSure&ranges_id=" . $delete['ranges_id']);
		echo tep_draw_hidden_field('ranges_id', $ranges_id);
		//echo tep_draw_hidden_field('gID', $gID);
		echo tep_image_submit('button_delete_b.gif', IMAGE_DELETE);
		echo '&nbsp;<a href="' . tep_href_link(FILENAME_RANGES_MANAGER, "", 'NONSSL') . '">' . tep_image_button('button_cancel_b.gif', IMAGE_CANCEL) . '</a>';
		echo "</form></td></tr>";
	} 
	else {$error="80";}
	break;


case "DelSure":
	if ($ranges_id = $_GET['ranges_id']) {
		
		//BOF RANGE LOGO 09-JAN-2014  
		//@unlink(RANGE_LOGO.$_POST['logoname']);
		$delogoQry = tep_db_query("SELECT `logo` from " . TABLE_RANGES . " where ranges_id = '" . (int)$ranges_id . "'");
		$delLogo = tep_db_fetch_array($delogoQry);
		//print_r($delLogo);exit;
		@unlink(RANGE_LOGO_PATH.$delLogo['logo']);
		//EOF RANGE LOGO 09-JAN-2014  
		tep_db_query("delete from " . TABLE_RANGES . " where ranges_id = '" . (int)$ranges_id . "'");tep_db_query("delete from " . TABLE_LANES . " where ranges_id = '" . (int)$ranges_id . "'");
		$title = "$confirm " . DELETED_ID_INFORMATION . " $ranges_id " . SUCCED_INFORMATION . "";
		include('ranges_list.php');
	} 
	else {$error="80";}
	break;

default:
	$data = tep_get_information_list();
	$title = MANAGER_INFORMATION . " <FONT SIZE='-1'>/ " . $info_group['information_group_title'] . "</FONT>";
	include('ranges_list.php');
	flush();
//	tep_update_information_languages();
} // END SWITCH


if ($error) {
	$content=error_message($error);
	echo $content;
	$data = tep_get_information_list();
	$no = 1;
	if (sizeof($data) > 0) {
		while (list($key, $val)=each($data)) {$no++; }	
	}
	$title = ADD_QUEUE_INFORMATION . " $no";
	echo tep_draw_form('',FILENAME_RANGES_MANAGER, 'range_action=AddSure');
	//echo tep_draw_hidden_field('gID', $gID);
	include('ranges_form.php');
}
?>
</table></td>


<!-- body_text_eof //-->
  </tr>
</table>
<!-- body_eof //-->

<!-- footer //-->
<?php require(DIR_WS_INCLUDES . 'footer.php'); ?>
<!-- footer_eof //-->
<br>
</body>
</html> 
<?php require(DIR_WS_INCLUDES . 'application_bottom.php'); ?>